name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/golangwebapp:latest
          
      -
        name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}


      - name: Send SonarQube analysis results to your existing cluster
        run: |
          # You can use the SonarScanner command or the SonarQube CLI to send results
          # to your existing SonarQube cluster. Replace the placeholders with your
          # SonarQube cluster's URL and authentication token.
          sonar-scanner \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=sqp_0658e89346c7832936b408166f69489d2e48cc44

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



