name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v2
      with:
        dockerfile: https://github.com/anishkasaxena/GoWebApp2.0/blob/main/Dockerfile

    - name: Build Docker image
      run: docker build -t anishka012/my-docker-image:latest

    - name: Log in to Docker Hub (if needed)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      run: docker push anishka012/my-docker-image:latest


  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SonarQube
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        projectKey: GoWeb-App
        projectName: GoWebApp2.0
        # organization: your_organization  # If applicable
        scannerVersion: latest

    - name: Run SonarQube analysis
      run: sonar-scanner  # Make sure SonarScanner is available in your Docker image

    - name: Upload SonarQube results
      uses: actions/upload-artifact@v2
      with:
        name: sonarqube-report
        path: .scannerwork

    - name: Complete SonarQube analysis
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        scannerVersion: latest
        waitForQualityGate: 'true'
